In [99]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [100]:
df=pd.read_excel('Trend Dataset.xlsx')
df.head()

,Search Term,Category,Division,Department,Search Frequency Rank,#1 Clicked ASIN,#1 Product Title,#1 Click Share,#1 Conversion Share,#2 Clicked ASIN,#2 Product Title,#2 Click Share,#2 Conversion Share,#3 Clicked ASIN,#3 Product Title,#3 Click Share,#3 Conversion Share
0,Wireless Mouse,Electronics,Computer,Accessories,1,B08L5G9D6Z,Logitech MX Master 3,0.25,0.15,B07X2H6FRZ,Razer DeathAdder V2,0.20,0.10,B07N7T8Q43,Corsair Harpoon RGB,0.15,0.08
1,Yoga Mat,Sports,Fitness,Equipment,2,B07W9R2Y7D,Liforme Yoga Mat,0.30,0.20,B01M12B7KD,Manduka PRO Yoga Mat,0.25,0.18,B08KJZ4NQ2,Gaiam Cork Yoga Block,0.20,0.12
2,Instant Pot,Kitchen,Appliances,Cookware,3,B07VLX69CC,Instant Pot Duo 7-in-1,0.40,0.25,B07W28H3M9,Ninja Foodi Pressure Cooker,0.30,0.20,B08F2XJ5CD,Cosori Air Fryer,0.25,0.15
3,Fitness Tracker,Wearables,Health,Accessories,4,B08D85HJ4L,Fitbit Charge 4,0.35,0.22,B07VGFHR9C,Garmin Vivosmart 4,0.28,0.19,B089QGV3S9,Amazfit Bip U Pro,0.20,0.10
4,Noise Cancelling Headphones,Electronics,Audio,Accessories,5,B07G7TT9B6,Sony WH-1000XM4,0.45,0.30,B08H6WTR8K,Bose QuietComfort 35 II,0.35,0.25,B07PP4B9FQ,Apple AirPods Max,0.30,0.18

In [101]:
df_new=df[df['Division']!='others']
df_rel=df_new[['Search Term','Division','Search Frequency Rank','Department','Category']]
df_rel=df_rel.drop('Department',axis=1)

In [102]:
df_rel['Relevant_Freq_Rank']=range(1,df_rel.shape[0]+1)

In [103]:
df_rel.head()

,Search Term,Division,Search Frequency Rank,Category,Relevant_Freq_Rank
0,Wireless Mouse,Computer,1,Electronics,1
1,Yoga Mat,Fitness,2,Sports,2
2,Instant Pot,Appliances,3,Kitchen,3
3,Fitness Tracker,Health,4,Wearables,4
4,Noise Cancelling Headphones,Audio,5,Electronics,5

In [104]:
df_rel['Trend_Score']=df_rel.shape[0]/df_rel['Relevant_Freq_Rank']

In [105]:
df_rel.head()

,Search Term,Division,Search Frequency Rank,Category,Relevant_Freq_Rank,Trend_Score
0,Wireless Mouse,Computer,1,Electronics,1,5.000000
1,Yoga Mat,Fitness,2,Sports,2,2.500000
2,Instant Pot,Appliances,3,Kitchen,3,1.666667
3,Fitness Tracker,Health,4,Wearables,4,1.250000
4,Noise Cancelling Headphones,Audio,5,Electronics,5,1.000000

In [106]:
df_rel['Division_Freq_Rank']=df_rel.groupby('Division')['Relevant_Freq_Rank'].rank("dense")

In [107]:
df_rel.head(5)

,Search Term,Division,Search Frequency Rank,Category,Relevant_Freq_Rank,Trend_Score,Division_Freq_Rank
0,Wireless Mouse,Computer,1,Electronics,1,5.000000,1.0
1,Yoga Mat,Fitness,2,Sports,2,2.500000,1.0
2,Instant Pot,Appliances,3,Kitchen,3,1.666667,1.0
3,Fitness Tracker,Health,4,Wearables,4,1.250000,1.0
4,Noise Cancelling Headphones,Audio,5,Electronics,5,1.000000,1.0

In [108]:
df_rel['Category_Freq_Rank']=df_rel.groupby('Category')['Relevant_Freq_Rank'].rank("dense")
df_rel.head()

,Search Term,Division,Search Frequency Rank,Category,Relevant_Freq_Rank,Trend_Score,Division_Freq_Rank,Category_Freq_Rank
0,Wireless Mouse,Computer,1,Electronics,1,5.000000,1.0,1.0
1,Yoga Mat,Fitness,2,Sports,2,2.500000,1.0,1.0
2,Instant Pot,Appliances,3,Kitchen,3,1.666667,1.0,1.0
3,Fitness Tracker,Health,4,Wearables,4,1.250000,1.0,1.0
4,Noise Cancelling Headphones,Audio,5,Electronics,5,1.000000,1.0,2.0

In [109]:
Max_Rank_For_Each=df_rel.groupby('Division')['Division_Freq_Rank'].max()
Max_Rank_For_Each

Division
Appliances    1.0
Audio         1.0
Computer      1.0
Fitness       1.0
Health        1.0
Name: Division_Freq_Rank, dtype: float64